### ISSUE TITLE
Not sure how to resolve the error

### ISSUE THREAD

**Issue by chenlomis** [hackathon-cli-recommendation/cli-recommendation#11]
![image](https://user-images.githubusercontent.com/30876406/109860517-1e545c00-7c13-11eb-965a-e18571ffbda2.png)
![image](https://user-images.githubusercontent.com/30876406/109860547-28765a80-7c13-11eb-8d6b-153e8bec63e2.png)

**Comment by chenlomis** [comment]
When we tried az next again:

![image](https://user-images.githubusercontent.com/30876406/109860672-493eb000-7c13-11eb-9918-5cf60ed260d3.png)

**Comment by zhoxing-ms** [comment]
@chenlomis I'd like to ask you what commands you executed before executing `az next`?

**Comment by chenlomis** [comment]
Of course! It was az group create

**Comment by chenlomis** [comment]
I think what happened could be that there was already a default group under the . config file and that setting a new one collided with the existing settings

**Comment by zhoxing-ms** [comment]
@chenlomis Actually, our recommendation is according to the latest two commands. Could you give me the last two commands? Otherwise, it is not easy for me to repeat this problem~
