### ISSUE TITLE
Slight Clarity Improvement

### ISSUE THREAD

**Issue by christiw16** [hackathon-cli-recommendation/cli-recommendation#12]
[WillFeedback]
<img width="516" alt="Screen Shot 2021-03-11 at 11 31 42 AM" src="https://user-images.githubusercontent.com/5742069/110843795-8a5f4180-825d-11eb-98bd-bd24cdce3d56.png">
 It would be slightly more clear if the mysubscription in "az account set --subscription mysubscription" was in quotes here to show it takes a string and how best to avoid issues with spaces. So it would be: az account set --subscription "mysubscription"

**Comment by zhoxing-ms** [comment]
Great suggestion, but this issue does not belong to `az next`. I will contact the relevant owner in charge, so I will close it here first.
