### ISSUE TITLE
Expecting a resolution, received next step recommendation

### ISSUE THREAD

**Issue by marcobaldo** [hackathon-cli-recommendation/cli-recommendation#15]
[MarcFeedback]
I was trying to create a new appservice plan and encountered an error (missing parameter). Following the sample from [guidance_for_az_next](https://github.com/hackathon-cli-recommendation/cli-recommendation/blob/master/Docs/guidance_for_az_next.md) under bullet 1 in How To Play, I was expecting it to recommend a guided `az appservice plan create`. However, I was immediately recommended to create a webapp.

Context: I came to create a new appservice plan because I was stuck at `az webapp create` having no appservice plan to create it in. If I keep on following `az next` here, I will end up in an infinite loop.

![appservice plan to webapp](https://user-images.githubusercontent.com/1984893/111241316-d6343100-8637-11eb-87ed-00d320fdf267.PNG)

**Comment by zhoxing-ms** [comment]
Thanks for your feedback, this problem has been solved~
