### ISSUE TITLE
The installation error of "az next"

### ISSUE THREAD

**Issue by zhoxing-ms** [hackathon-cli-recommendation/cli-recommendation#5]
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62
Instead of https://github.com/Azure/azure-cli/issues/16601

**Describe the bug**
![image](https://user-images.githubusercontent.com/30876406/105226337-b8a18a00-5b14-11eb-9bfc-bcead1cbc45f.png)

Have actually encountered similar errors like this numerous times in the last weeks but never created a bug to track it until now

**To Reproduce**
1) tried az next after upgrading to v2.18.0 but didn't work
2) tried uninstalling and reinstalling the feature ...also didn't work...

**Expected behavior**
 I expect anyone using the feature not to encounter error every time they use the feature after version upgrade or for any other reason
 
**Environment summary**
![image](https://user-images.githubusercontent.com/30876406/105226561-fd2d2580-5b14-11eb-9c80-c35da5a66902.png)

**Additional context**

**Comment by zhoxing-ms** [comment]
@chenlomis May I ask has this problem been solved?

**Comment by chenlomis** [comment]
Yes it has! Thank you very much
I did encounter another interesting issue though... Maybe I could create a new one to track it
