### ISSUE TITLE
The installation error of az next v2...

### ISSUE THREAD

**Issue by chenlomis** [hackathon-cli-recommendation/cli-recommendation#7]
Hi Xing...

I reattempted the download after your tweaks but am encountering the same installation issue as before

![image](https://user-images.githubusercontent.com/30876406/105653572-ff72e500-5e70-11eb-858c-c25fa8cebb61.png)

Tried it with both the regular terminal and admin terminal too
And tried reopening the same terminal but no luck..

**Comment by zhoxing-ms** [comment]
Hi @chenlomis 
May I ask how you installed `az next` before in your current environment?
Could you please use `az vesion` to show me the current version information?

**Comment by chenlomis** [comment]
Yes of course
I uninstalled the extension and then tried to re-install it 
Same as previous times

Here's the versioning info. Still v2.18.0
![image](https://user-images.githubusercontent.com/30876406/105670589-2099fc80-5e96-11eb-8056-5fb73c0be426.png)

**Comment by zhoxing-ms** [comment]
@chenlomis Could you please show me all the information printed by `az version`?

**Comment by chenlomis** [comment]
Yup
here we go
![image](https://user-images.githubusercontent.com/30876406/105671085-fac12780-5e96-11eb-869f-d862a1dc1e52.png)

**Comment by zhoxing-ms** [comment]
@chenlomis OK, I will send you an MSI package through teams, please execute this installation package and have a try~

**Comment by zhoxing-ms** [comment]
@chenlomis May I ask has this problem been solved?

**Comment by chenlomis** [comment]
Yes thank you Xing!
